In [2]:
import numpy as np 
import pandas as pd

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
credits= pd.read_csv(r"C:\Users\User\Documents\Movie Reccomender Project\.CSV\tmdb_5000_credits.csv")
movie = pd.read_csv(r"C:\Users\User\Downloads\TMDB_movie_dataset_v11.csv")

In [5]:
credits.head(1)
movie.head(1)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."

In [6]:
movie.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='object')

In [7]:
movies = movie.merge(credits,on='title')

In [8]:
movies.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [9]:
##genre 
## ID 
## Keyword
##Title
## Overview
##cast 
## crew

movies = movies[['id','title','keywords','overview','cast','crew','genres']]

In [10]:
movies.head()

,id,title,keywords,overview,cast,crew,genres
0,27205,Inception,"rescue, mission, dream, airplane, paris, franc...","Cobb, a skilled thief who commits corporate es...","[{""cast_id"": 1, ""character"": ""Dom Cobb"", ""cred...","[{""credit_id"": ""56e8462cc3a368408400354c"", ""de...","Action, Science Fiction, Adventure"
1,1352799,Inception,NaN,"As James lives his quiet life, his mind is ful...","[{""cast_id"": 1, ""character"": ""Dom Cobb"", ""cred...","[{""credit_id"": ""56e8462cc3a368408400354c"", ""de...",Horror
2,1394217,Inception,NaN,"Dom Cobb is a skilled thief, the best in the f...","[{""cast_id"": 1, ""character"": ""Dom Cobb"", ""cred...","[{""credit_id"": ""56e8462cc3a368408400354c"", ""de...",NaN
3,157336,Interstellar,"rescue, future, spacecraft, race against time,...",The adventures of a group of explorers who mak...,"[{""cast_id"": 9, ""character"": ""Joseph Cooper"", ...","[{""credit_id"": ""52fe4bbf9251416c910e4801"", ""de...","Adventure, Drama, Science Fiction"
4,155,The Dark Knight,"joker, sadism, chaos, secret identity, crime f...",Batman raises the stakes in his war on crime. ...,"[{""cast_id"": 35, ""character"": ""Bruce Wayne"", ""...","[{""credit_id"": ""55a0eb4a925141296b0010f8"", ""de...","Drama, Action, Crime, Thriller"

In [11]:
movies.isnull().sum()

id              0
title           0
keywords    10125
overview     1408
cast            0
crew            0
genres       4903
dtype: int64

In [12]:
movies.duplicated().sum()

6

In [13]:
movies.dropna(inplace=True)

In [14]:
movies.iloc[0].cast

'[{"cast_id": 1, "character": "Dom Cobb", "credit_id": "52fe4534c3a368484e04de03", "gender": 2, "id": 6193, "name": "Leonardo DiCaprio", "order": 0}, {"cast_id": 3, "character": "Arthur", "credit_id": "52fe4534c3a368484e04de0b", "gender": 2, "id": 24045, "name": "Joseph Gordon-Levitt", "order": 1}, {"cast_id": 5, "character": "Ariadne", "credit_id": "52fe4534c3a368484e04de13", "gender": 1, "id": 27578, "name": "Ellen Page", "order": 2}, {"cast_id": 7, "character": "Eames", "credit_id": "52fe4534c3a368484e04de1b", "gender": 2, "id": 2524, "name": "Tom Hardy", "order": 3}, {"cast_id": 2, "character": "Saito", "credit_id": "52fe4534c3a368484e04de07", "gender": 2, "id": 3899, "name": "Ken Watanabe", "order": 4}, {"cast_id": 8, "character": "Robert Fischer", "credit_id": "52fe4534c3a368484e04de1f", "gender": 2, "id": 2037, "name": "Cillian Murphy", "order": 5}, {"cast_id": 4, "character": "Mal", "credit_id": "52fe4534c3a368484e04de0f", "gender": 1, "id": 8293, "name": "Marion Cotillard", "order": 6}, {"cast_id": 6, "character": "Miles", "credit_id": "52fe4534c3a368484e04de17", "gender": 2, "id": 3895, "name": "Michael Caine", "order": 7}, {"cast_id": 19, "character": "Yusuf", "credit_id": "52fe4534c3a368484e04de4f", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 8}, {"cast_id": 9, "character": "Browning", "credit_id": "52fe4534c3a368484e04de23", "gender": 2, "id": 13022, "name": "Tom Berenger", "order": 9}, {"cast_id": 22, "character": "Maurice Fischer", "credit_id": "52fe4534c3a368484e04de59", "gender": 2, "id": 4935, "name": "Pete Postlethwaite", "order": 10}, {"cast_id": 10, "character": "Nash", "credit_id": "52fe4534c3a368484e04de27", "gender": 2, "id": 526, "name": "Lukas Haas", "order": 11}, {"cast_id": 89, "character": "Blonde", "credit_id": "52fe4534c3a368484e04de99", "gender": 1, "id": 66441, "name": "Talulah Riley", "order": 12}, {"cast_id": 92, "character": "Japanese Security Guard", "credit_id": "57d488dec3a3685568007ba1", "gender": 0, "id": 173212, "name": "Tohoru Masamune", "order": 13}, {"cast_id": 93, "character": "Phillipa (5 years)", "credit_id": "57d488f8c3a368154b0011a1", "gender": 1, "id": 967376, "name": "Taylor Geare", "order": 14}, {"cast_id": 94, "character": "Phillipa (3 years)", "credit_id": "57d48919925141382f0011ca", "gender": 1, "id": 973135, "name": "Claire Geare", "order": 15}, {"cast_id": 95, "character": "James (3 years)", "credit_id": "57d48aca925141369d00113d", "gender": 2, "id": 1677266, "name": "Johnathan Geare", "order": 16}, {"cast_id": 96, "character": "Saito\'s Attendant", "credit_id": "57d48b45c3a3680b9f00179e", "gender": 2, "id": 56120, "name": "Yuji Okumoto", "order": 17}, {"cast_id": 97, "character": "Elderly Bald Man", "credit_id": "57d48b59c3a3685568007cd7", "gender": 2, "id": 2246, "name": "Earl Cameron", "order": 18}, {"cast_id": 98, "character": "Lawyer", "credit_id": "57d48b6dc3a3680ccd001433", "gender": 2, "id": 1677267, "name": "Ryan Hayward", "order": 19}, {"cast_id": 99, "character": "Flight Attendant", "credit_id": "57d48b84925141382f0012af", "gender": 1, "id": 1334309, "name": "Miranda Nolan", "order": 20}, {"cast_id": 100, "character": "Cab Driver", "credit_id": "57d53da09251415c1e000263", "gender": 2, "id": 535, "name": "Russ Fega", "order": 21}, {"cast_id": 101, "character": "Thin Man", "credit_id": "57d53db4c3a368556800ce41", "gender": 2, "id": 72864, "name": "Tim Kelleher", "order": 22}, {"cast_id": 102, "character": "Bridge Sub Con", "credit_id": "57d53e46c3a36812b2000308", "gender": 1, "id": 1677498, "name": "Coralie Dedykere", "order": 23}, {"cast_id": 103, "character": "Bridge Sub Con", "credit_id": "57d53ee6c3a3686e3c000cd9", "gender": 0, "id": 13695, "name": "Silvie Laguna", "order": 24}, {"cast_id": 104, "character": "Bridge Sub Con", "credit_id": "57d53efcc3a36813230002f5", "gender": 2, "id": 133257, "name": "Virgile Bramly", "order": 25}, {"cast_id": 105, "character": "Bridge Sub Con", "credit_id": "57d53fde9251415c1e000324", "gender": 2, "id": 1677507, "name": "Nicolas Clerc", "order": 26}, {"cast_id": 106, "character": "Bridge Sub Con", "credit_id": "57d5405f9251415bb300037f", "gender": 2, "id": 1536351, "name": "Jean-Michel Dagory", "order": 27}, {"cast_id": 107, "character": "Lobby Sub Con", "credit_id": "57d540c7c3a36813230003bc", "gender": 2, "id": 203087, "name": "Marc Raducci", "order": 28}]'

In [15]:
import ast

def convert(obj):
    L = []
    for i in ast.literal_eval(obj) :
        L.append(i['name'])
        return L

In [16]:
#movies['genres'].apply(convert)

In [17]:
movies.head()

,id,title,keywords,overview,cast,crew,genres
0,27205,Inception,"rescue, mission, dream, airplane, paris, franc...","Cobb, a skilled thief who commits corporate es...","[{""cast_id"": 1, ""character"": ""Dom Cobb"", ""cred...","[{""credit_id"": ""56e8462cc3a368408400354c"", ""de...","Action, Science Fiction, Adventure"
3,157336,Interstellar,"rescue, future, spacecraft, race against time,...",The adventures of a group of explorers who mak...,"[{""cast_id"": 9, ""character"": ""Joseph Cooper"", ...","[{""credit_id"": ""52fe4bbf9251416c910e4801"", ""de...","Adventure, Drama, Science Fiction"
4,155,The Dark Knight,"joker, sadism, chaos, secret identity, crime f...",Batman raises the stakes in his war on crime. ...,"[{""cast_id"": 35, ""character"": ""Bruce Wayne"", ""...","[{""credit_id"": ""55a0eb4a925141296b0010f8"", ""de...","Drama, Action, Crime, Thriller"
6,19995,Avatar,"future, society, culture clash, space travel, ...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","Action, Adventure, Fantasy, Science Fiction"
13,24428,The Avengers,"new york city, superhero, shield, based on com...",When an unexpected enemy emerges and threatens...,"[{""cast_id"": 46, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""52fe4495c3a368484e02b1cf"", ""de...","Science Fiction, Action, Adventure"

In [18]:
import ast

def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [19]:
movies['cast'] = movies['cast'].apply(convert3)

In [20]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])
movies.head(1)

,id,title,keywords,overview,cast,crew,genres
0,27205,Inception,"rescue, mission, dream, airplane, paris, franc...","Cobb, a skilled thief who commits corporate es...","[Leonardo DiCaprio, Joseph Gordon-Levitt, Elle...","[{""credit_id"": ""56e8462cc3a368408400354c"", ""de...","Action, Science Fiction, Adventure"

In [21]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [22]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [23]:
#movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(5)

,id,title,keywords,overview,cast,crew,genres
6294,16614,Adventureland,"infidelity, amusement park, summer job, carny,...","In the summer of 1987, a college graduate take...","[Jesse Eisenberg, Kristen Stewart, Martin Starr]",[Greg Mottola],"Comedy, Drama"
1127,128,Princess Mononoke,"friendship, human vs nature, wolf, fight, wild...","Ashitaka, a prince of the disappearing Emishi ...","[Yōji Matsuda, Yuriko Ishida, Yūko Tanaka]",[Hayao Miyazaki],"Adventure, Fantasy, Animation"
15819,17622,Fifty Dead Men Walking,"ira (irish republican army), slot machine, rio...","It's 1989, and in a Belfast torn apart by conf...","[Ben Kingsley, Jim Sturgess, Kevin Zegers]",[Kari Skogland],"Action, Thriller"
9222,793502,Dracula,based on novel or book,A futuristic sci-fi western version of Dracula.,"[Gary Oldman, Winona Ryder, Anthony Hopkins]",[Francis Ford Coppola],"Science Fiction, Western, Horror"
18320,324352,Anderson's Cross,"coming of age, gay theme","Nick Anderson, Kevin Daniels, and Tracey Green...","[Joanna Cassidy, Joyce Guy, Bill Moseley]",[Jerome Elston Scott],"Romance, Comedy, Drama"

In [24]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [25]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)

In [26]:
movies.head(5)

,id,title,keywords,overview,cast,crew,genres
0,27205,Inception,"rescue, mission, dream, airplane, paris, franc...","Cobb, a skilled thief who commits corporate es...","[LeonardoDiCaprio, JosephGordon-Levitt, EllenP...",[ChristopherNolan],"Action, Science Fiction, Adventure"
3,157336,Interstellar,"rescue, future, spacecraft, race against time,...",The adventures of a group of explorers who mak...,"[MatthewMcConaughey, JessicaChastain, AnneHath...",[ChristopherNolan],"Adventure, Drama, Science Fiction"
4,155,The Dark Knight,"joker, sadism, chaos, secret identity, crime f...",Batman raises the stakes in his war on crime. ...,"[ChristianBale, HeathLedger, AaronEckhart]",[ChristopherNolan],"Drama, Action, Crime, Thriller"
6,19995,Avatar,"future, society, culture clash, space travel, ...","In the 22nd century, a paraplegic Marine is di...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"Action, Adventure, Fantasy, Science Fiction"
13,24428,The Avengers,"new york city, superhero, shield, based on com...",When an unexpected enemy emerges and threatens...,"[RobertDowneyJr., ChrisEvans, MarkRuffalo]",[JossWhedon],"Science Fiction, Action, Adventure"

In [27]:
movies['tags'] = (
    movies['overview'] +
    " " + movies['genres'].apply(lambda x: " ".join(x)) +
    " " + movies['keywords'] +
    " " + movies['cast'].apply(lambda x: " ".join(x)) +
    " " + movies['crew'].apply(lambda x: " ".join(x))
)

In [28]:
movies.head(1)

,id,title,keywords,overview,cast,crew,genres,tags
0,27205,Inception,"rescue, mission, dream, airplane, paris, franc...","Cobb, a skilled thief who commits corporate es...","[LeonardoDiCaprio, JosephGordon-Levitt, EllenP...",[ChristopherNolan],"Action, Science Fiction, Adventure","Cobb, a skilled thief who commits corporate es..."

In [29]:
movies.drop(columns={'keywords','overview','cast','crew','genres'})

,id,title,tags
0,27205,Inception,"Cobb, a skilled thief who commits corporate es..."
3,157336,Interstellar,The adventures of a group of explorers who mak...
4,155,The Dark Knight,Batman raises the stakes in his war on crime. ...
6,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
13,24428,The Avengers,When an unexpected enemy emerges and threatens...
...,...,...,...
18426,1624707,Three Men and a Baby,Remake of the 1987 film that put three bachelo...
18427,699457,Three Men and a Baby,Life for an NYC bachelor and his two single fr...
18431,288927,Archaeology of a Woman,A woman's dementia uncovers secrets of a 30-ye...
18439,354624,Heroes of Dirt,"Passionate BMX dirt jumper, Phin Cooper, wants..."
18441,364083,Mi America,A hate-crime has been committed in a the small...

In [30]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:

import nltk

In [32]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [33]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [34]:
movies['tags'] = movies['tags'].apply(stem)

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [36]:
vector=cv.fit_transform(movies['tags']).toarray()

In [37]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
similarity=cosine_similarity(vector)

In [40]:
similarity[0]

array([1.        , 0.05518948, 0.04243489, ..., 0.03615508, 0.09901475,
       0.03212463])

In [41]:
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [42]:
recommend('Avatar')

Much Ado About Nothing
Much Ado About Nothing
Flipped
Endless Love
The Road

In [43]:

import pickle

In [44]:
import pickle

# Save the movies dataframe
pickle.dump(movies, open('movie_list.pkl', 'wb'))

# Save the similarity matrix
pickle.dump(similarity, open('similarity.pkl', 'wb'))

print("Done! Files saved.")

Done! Files saved.

In [45]:
import os
print(os.getcwd())  # This prints the folder where the files were saved

c:\Users\User\Downloads